# Generated by Django 5.1.6 on 2025-02-15 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='horario',
            field=models.CharField(max_length=30, verbose_name='Horário'),
        ),
    ]
