# Generated by Django 5.1.6 on 2025-02-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_historico_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disciplina',
            name='nome',
            field=models.CharField(max_length=30, verbose_name='Disciplina'),
        ),
    ]
