# Generated by Django 5.1.6 on 2025-02-16 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_disciplina_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historico',
            name='semestre',
            field=models.FloatField(verbose_name='Semestre'),
        ),
    ]
